// this file was generated by configure.sh.
#undef HAVE_POWI
#define HAVE_POW_DOUBLE_INT 1
#define HAVE_POW_DOUBLE_LONG 1
#define HAVE_POW_FLOAT_INT 1
#define HAVE_POW_FLOAT_LONG 1
#define HAVE_POW_DOUBLE_FLOAT 1
#define HAVE_POW_FLOAT_DOUBLE 1
#define HAVE_FUNC 1
#define HAVE_ERF 1
#define HAVE_ERFC 1
#define HAVE_SINCOS 1
#define HAVE_LONG_LONG 1
#define HAVE_STRNLEN 1
#undef HAVE_CONSTEXPR
#define HAVE_REALPATH 1
#define HAVE_AVX_INTRIN 1
#define HAVE_FMA_INTRIN 1
#define HAVE_AVX2_INTRIN 1
#undef HAVE_AVX512F_INTRIN
