#!/bin/bash

#SBATCH --job-name="py-emm"
#SBATCH --mail-type=NONE         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=alankardutta@iisc.ac.in    # Where to send mail.  Set this to your email address
#SBATCH -p debug
#SBATCH -t 2-06:00:00
#SBATCH -n 192
#SBATCH --output=%x-%j.log

echo "Working Directory = $(pwd)"

cd $SLURM_SUBMIT_DIR
export PROG="/modules/comp_libs/anaconda3/bin/python generateCloudyScript-parallel.py"

module load mpich/4.0

srun $PROG
