name: AstroPlasma Unit Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
jobs:
  e2e_testing:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      name: Checkout repository
    - uses: actions/setup-python@v4
      name: Install python and load cache
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - run: sed -i.bak "s/3\.11/${{ matrix.python-version }}/g" requirements/requirements.txt
      if: matrix.python-version == '3.10'
      name: Prepare the requirements file python version
      shell: bash
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - run: pytest
      name: Run python tests
      env:
        PYTHONPATH: ${{ github.workspace }}
